FROM ubuntu:xenial
MAINTAINER Chris Scutcher <chris.scutcher@ninebysix.co.uk>
RUN apt-get update && apt-get install -y \
    bash \
    lighttpd \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["/bin/docker-http-server.sh"]
EXPOSE 80
VOLUME /var/www/localhost/htdocs

COPY lighttpd-common.conf /etc/lighttpd/lighttpd-common.conf
COPY lighttpd-xenial.conf /etc/lighttpd/lighttpd.conf

COPY docker-http-server.sh /bin
RUN chmod o+x /bin/docker-http-server.sh

ENV HTTPD_USER www-data
